name: Build Android Navigation Bar RootHide

on:
  workflow_dispatch:

    branches:
      - main
    paths:
      - "Makefile"
      - "control"
      - "Tweak.xm"
      - "AndroidNavigationBar.plist"
      - ".github/workflows/build.yml"

permissions:
  contents: read

jobs:

  build:

    runs-on: macos-14

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          set -e

          brew update

          brew install \
            ldid \
            make \
            xz \
            dpkg

          echo "$(brew --prefix make)/libexec/gnubin" \
            >> "$GITHUB_PATH"


      - name: Install RootHide Theos
        run: |
          set -e

          rm -rf "$GITHUB_WORKSPACE/theos"

          git clone \
            --recursive \
            --depth 1 \
            https://github.com/roothide/theos.git \
            "$GITHUB_WORKSPACE/theos"

          echo "THEOS=$GITHUB_WORKSPACE/theos" \
            >> "$GITHUB_ENV"


      - name: Install iOS 16.5 SDK
        run: |
          set -e

          mkdir -p "$THEOS/sdks"

          rm -rf "$RUNNER_TEMP/theos-sdks"

          git clone \
            --depth 1 \
            --filter=blob:none \
            --sparse \
            https://github.com/theos/sdks.git \
            "$RUNNER_TEMP/theos-sdks"

          cd "$RUNNER_TEMP/theos-sdks"

          git sparse-checkout set \
            iPhoneOS16.5.sdk

          rm -rf \
            "$THEOS/sdks/iPhoneOS16.5.sdk"

          cp -R \
            iPhoneOS16.5.sdk \
            "$THEOS/sdks/iPhoneOS16.5.sdk"


      - name: Clean
        run: |
          set -e

          rm -rf packages
          rm -rf .theos

          make clean


      - name: Build
        run: |
          set -e

          make \
            package \
            FINALPACKAGE=1 \
            DEBUG=0 \
            THEOS_PACKAGE_SCHEME=roothide


      - name: Show package
        run: |
          set -e

          find packages \
            -type f \
            -name "*.deb" \
            -print

          ls -lh packages/*.deb


      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: AndroidNavigationBar-RootHide-arm64e
          path: packages/*.deb
          if-no-files-found: error
          compression-level: 0
